// Auto-generated by LibreLane
module soc_top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk_i,
  input rst_ni,
  input[31:0] gpio0_in,
  output[31:0] gpio0_out,
  output[31:0] gpio0_dir,
  input[31:0] gpio1_in,
  output[31:0] gpio1_out,
  output[31:0] gpio1_dir,
  input[31:0] gpio2_in,
  output[31:0] gpio2_out,
  output[31:0] gpio2_dir,
  output spi_cs_n,
  output spi_sclk,
  output spi_mosi,
  input spi_miso
);
endmodule
