// Auto-generated by LibreLane
module boot_spi_macro(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk_i,
  input rst_ni,
  output cpu_rst_n,
  output boot_we,
  output[31:0] boot_addr,
  output[31:0] boot_wdata,
  output spi_cs_n,
  output spi_sclk,
  output spi_mosi,
  input spi_miso,
  output boot_done
);
endmodule
