// Auto-generated by LibreLane
module picorv32_macro(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk_i,
  input rst_ni,
  output trap,
  output mem_axi_awvalid,
  input mem_axi_awready,
  output[31:0] mem_axi_awaddr,
  output[2:0] mem_axi_awprot,
  output mem_axi_wvalid,
  input mem_axi_wready,
  output[31:0] mem_axi_wdata,
  output[3:0] mem_axi_wstrb,
  input[1:0] mem_axi_bresp,
  input mem_axi_bvalid,
  output mem_axi_bready,
  output mem_axi_arvalid,
  input mem_axi_arready,
  output[31:0] mem_axi_araddr,
  output[2:0] mem_axi_arprot,
  input[1:0] mem_axi_rresp,
  input mem_axi_rvalid,
  output mem_axi_rready,
  input[31:0] mem_axi_rdata
);
endmodule
