/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module ram_macro(clk_i, rst_ni, s_axil_awaddr, s_axil_awvalid, s_axil_awready, s_axil_wdata, s_axil_wstrb, s_axil_wvalid, s_axil_wready, s_axil_bresp, s_axil_bvalid, s_axil_bready, s_axil_araddr, s_axil_arvalid, s_axil_arready, s_axil_rdata, s_axil_rresp, s_axil_rvalid, s_axil_rready, boot_we, boot_addr
, boot_wdata);
  input clk_i;
  wire clk_i;
  input rst_ni;
  wire rst_ni;
  input [31:0] s_axil_awaddr;
  wire [31:0] s_axil_awaddr;
  input s_axil_awvalid;
  wire s_axil_awvalid;
  output s_axil_awready;
  wire s_axil_awready;
  input [31:0] s_axil_wdata;
  wire [31:0] s_axil_wdata;
  input [3:0] s_axil_wstrb;
  wire [3:0] s_axil_wstrb;
  input s_axil_wvalid;
  wire s_axil_wvalid;
  output s_axil_wready;
  wire s_axil_wready;
  output [1:0] s_axil_bresp;
  wire [1:0] s_axil_bresp;
  output s_axil_bvalid;
  wire s_axil_bvalid;
  input s_axil_bready;
  wire s_axil_bready;
  input [31:0] s_axil_araddr;
  wire [31:0] s_axil_araddr;
  input s_axil_arvalid;
  wire s_axil_arvalid;
  output s_axil_arready;
  wire s_axil_arready;
  output [31:0] s_axil_rdata;
  wire [31:0] s_axil_rdata;
  output [1:0] s_axil_rresp;
  wire [1:0] s_axil_rresp;
  output s_axil_rvalid;
  wire s_axil_rvalid;
  input s_axil_rready;
  wire s_axil_rready;
  input boot_we;
  wire boot_we;
  input [31:0] boot_addr;
  wire [31:0] boot_addr;
  input [31:0] boot_wdata;
  wire [31:0] boot_wdata;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire aw_pending_q;
  wire \awaddr_q[10] ;
  wire \awaddr_q[11] ;
  wire \awaddr_q[2] ;
  wire \awaddr_q[3] ;
  wire \awaddr_q[4] ;
  wire \awaddr_q[5] ;
  wire \awaddr_q[6] ;
  wire \awaddr_q[7] ;
  wire \awaddr_q[8] ;
  wire \awaddr_q[9] ;
  wire \read_addr_q[0] ;
  wire \read_addr_q[1] ;
  wire \read_addr_q[2] ;
  wire \read_addr_q[3] ;
  wire \read_addr_q[4] ;
  wire \read_addr_q[5] ;
  wire \read_addr_q[6] ;
  wire \read_addr_q[7] ;
  wire \read_addr_q[8] ;
  wire \read_addr_q[9] ;
  wire \read_state_q[1] ;
  wire \read_state_q[2] ;
  wire \sram_addr[0] ;
  wire \sram_addr[1] ;
  wire \sram_addr[2] ;
  wire \sram_addr[3] ;
  wire \sram_addr[4] ;
  wire \sram_addr[5] ;
  wire \sram_addr[6] ;
  wire \sram_addr[7] ;
  wire \sram_addr[8] ;
  wire \sram_addr[9] ;
  wire \sram_bm[0] ;
  wire \sram_bm[10] ;
  wire \sram_bm[16] ;
  wire \sram_bm[24] ;
  wire \sram_din[0] ;
  wire \sram_din[10] ;
  wire \sram_din[11] ;
  wire \sram_din[12] ;
  wire \sram_din[13] ;
  wire \sram_din[14] ;
  wire \sram_din[15] ;
  wire \sram_din[16] ;
  wire \sram_din[17] ;
  wire \sram_din[18] ;
  wire \sram_din[19] ;
  wire \sram_din[1] ;
  wire \sram_din[20] ;
  wire \sram_din[21] ;
  wire \sram_din[22] ;
  wire \sram_din[23] ;
  wire \sram_din[24] ;
  wire \sram_din[25] ;
  wire \sram_din[26] ;
  wire \sram_din[27] ;
  wire \sram_din[28] ;
  wire \sram_din[29] ;
  wire \sram_din[2] ;
  wire \sram_din[30] ;
  wire \sram_din[31] ;
  wire \sram_din[3] ;
  wire \sram_din[4] ;
  wire \sram_din[5] ;
  wire \sram_din[6] ;
  wire \sram_din[7] ;
  wire \sram_din[8] ;
  wire \sram_din[9] ;
  wire \sram_dout[0] ;
  wire \sram_dout[10] ;
  wire \sram_dout[11] ;
  wire \sram_dout[12] ;
  wire \sram_dout[13] ;
  wire \sram_dout[14] ;
  wire \sram_dout[15] ;
  wire \sram_dout[1] ;
  wire \sram_dout[2] ;
  wire \sram_dout[3] ;
  wire \sram_dout[4] ;
  wire \sram_dout[5] ;
  wire \sram_dout[6] ;
  wire \sram_dout[7] ;
  wire \sram_dout[8] ;
  wire \sram_dout[9] ;
  wire sram_men;
  wire sram_ren;
  wire sram_wen;
  wire w_pending_q;
  wire \wdata_q[0] ;
  wire \wdata_q[10] ;
  wire \wdata_q[11] ;
  wire \wdata_q[12] ;
  wire \wdata_q[13] ;
  wire \wdata_q[14] ;
  wire \wdata_q[15] ;
  wire \wdata_q[16] ;
  wire \wdata_q[17] ;
  wire \wdata_q[18] ;
  wire \wdata_q[19] ;
  wire \wdata_q[1] ;
  wire \wdata_q[20] ;
  wire \wdata_q[21] ;
  wire \wdata_q[22] ;
  wire \wdata_q[23] ;
  wire \wdata_q[24] ;
  wire \wdata_q[25] ;
  wire \wdata_q[26] ;
  wire \wdata_q[27] ;
  wire \wdata_q[28] ;
  wire \wdata_q[29] ;
  wire \wdata_q[2] ;
  wire \wdata_q[30] ;
  wire \wdata_q[31] ;
  wire \wdata_q[3] ;
  wire \wdata_q[4] ;
  wire \wdata_q[5] ;
  wire \wdata_q[6] ;
  wire \wdata_q[7] ;
  wire \wdata_q[8] ;
  wire \wdata_q[9] ;
  wire \wstrb_q[0] ;
  wire \wstrb_q[1] ;
  wire \wstrb_q[2] ;
  wire \wstrb_q[3] ;
  sg13g2_inv_1 _419_ (
    .A(_017_),
    .Y(_113_)
  );
  sg13g2_nor2_1 _420_ (
    .A(s_axil_araddr[16]),
    .B(s_axil_araddr[19]),
    .Y(_114_)
  );
  sg13g2_nor4_1 _421_ (
    .A(s_axil_araddr[18]),
    .B(s_axil_araddr[21]),
    .C(s_axil_araddr[20]),
    .D(s_axil_araddr[23]),
    .Y(_115_)
  );
  sg13g2_and2_1 _422_ (
    .A(_114_),
    .B(_115_),
    .X(_116_)
  );
  sg13g2_nor4_2 _423_ (
    .A(s_axil_araddr[24]),
    .B(s_axil_araddr[27]),
    .C(s_axil_araddr[26]),
    .D(s_axil_araddr[29]),
    .Y(_117_)
  );
  sg13g2_nor4_2 _424_ (
    .A(s_axil_araddr[28]),
    .B(s_axil_araddr[31]),
    .C(s_axil_araddr[30]),
    .D(s_axil_araddr[1]),
    .Y(_118_)
  );
  sg13g2_nor4_2 _425_ (
    .A(s_axil_araddr[12]),
    .B(s_axil_araddr[15]),
    .C(s_axil_araddr[14]),
    .D(s_axil_araddr[17]),
    .Y(_119_)
  );
  sg13g2_nor4_2 _426_ (
    .A(s_axil_araddr[13]),
    .B(s_axil_araddr[22]),
    .C(s_axil_araddr[25]),
    .D(s_axil_araddr[0]),
    .Y(_120_)
  );
  sg13g2_and4_1 _427_ (
    .A(_117_),
    .B(_118_),
    .C(_119_),
    .D(_120_),
    .X(_121_)
  );
  sg13g2_inv_1 _428_ (
    .A(aw_pending_q),
    .Y(_122_)
  );
  sg13g2_inv_1 _429_ (
    .A(w_pending_q),
    .Y(_123_)
  );
  sg13g2_nor4_2 _430_ (
    .A(boot_we),
    .B(s_axil_bvalid),
    .C(s_axil_rvalid),
    .D(_017_),
    .Y(_124_)
  );
  sg13g2_and4_1 _431_ (
    .A(_122_),
    .B(_123_),
    .C(s_axil_arvalid),
    .D(_124_),
    .X(_125_)
  );
  sg13g2_nand3_1 _432_ (
    .A(_116_),
    .B(_121_),
    .C(_125_),
    .Y(_126_)
  );
  sg13g2_a21oi_1 _433_ (
    .A1(_113_),
    .A2(_126_),
    .B1(\read_state_q[1] ),
    .Y(_018_)
  );
  sg13g2_inv_1 _434_ (
    .A(\wdata_q[5] ),
    .Y(_127_)
  );
  sg13g2_nor4_2 _435_ (
    .A(s_axil_awaddr[27]),
    .B(s_axil_awaddr[26]),
    .C(s_axil_awaddr[29]),
    .D(s_axil_awaddr[28]),
    .Y(_128_)
  );
  sg13g2_nor4_2 _436_ (
    .A(s_axil_awaddr[31]),
    .B(s_axil_awaddr[30]),
    .C(s_axil_awaddr[1]),
    .D(s_axil_awaddr[0]),
    .Y(_129_)
  );
  sg13g2_nor4_2 _437_ (
    .A(s_axil_awaddr[15]),
    .B(s_axil_awaddr[14]),
    .C(s_axil_awaddr[17]),
    .D(s_axil_awaddr[16]),
    .Y(_130_)
  );
  sg13g2_nor4_2 _438_ (
    .A(s_axil_awaddr[13]),
    .B(s_axil_awaddr[12]),
    .C(s_axil_awaddr[25]),
    .D(s_axil_awaddr[24]),
    .Y(_131_)
  );
  sg13g2_and4_1 _439_ (
    .A(_128_),
    .B(_129_),
    .C(_130_),
    .D(_131_),
    .X(_132_)
  );
  sg13g2_buf_16 _440_ (
    .A(_132_),
    .X(_133_)
  );
  sg13g2_or2_1 _441_ (
    .A(s_axil_bvalid),
    .B(_017_),
    .X(_134_)
  );
  sg13g2_buf_1 _442_ (
    .A(_134_),
    .X(_135_)
  );
  sg13g2_nand3b_1 _443_ (
    .A_N(boot_we),
    .B(aw_pending_q),
    .C(w_pending_q),
    .Y(_136_)
  );
  sg13g2_or4_1 _444_ (
    .A(s_axil_awaddr[18]),
    .B(s_axil_awaddr[21]),
    .C(s_axil_awaddr[20]),
    .D(s_axil_awaddr[22]),
    .X(_137_)
  );
  sg13g2_or2_1 _445_ (
    .A(s_axil_awaddr[19]),
    .B(s_axil_awaddr[23]),
    .X(_138_)
  );
  sg13g2_nor4_2 _446_ (
    .A(_135_),
    .B(_136_),
    .C(_137_),
    .D(_138_),
    .Y(_139_)
  );
  sg13g2_buf_8 _447_ (
    .A(_139_),
    .X(_140_)
  );
  sg13g2_nand2_2 _448_ (
    .A(_133_),
    .B(_140_),
    .Y(_141_)
  );
  sg13g2_buf_8 _449_ (
    .A(_141_),
    .X(_142_)
  );
  sg13g2_nand2_1 _450_ (
    .A(boot_wdata[5]),
    .B(boot_we),
    .Y(_143_)
  );
  sg13g2_o21ai_1 _451_ (
    .A1(_127_),
    .A2(_142_),
    .B1(_143_),
    .Y(\sram_din[5] )
  );
  sg13g2_inv_1 _452_ (
    .A(\wdata_q[6] ),
    .Y(_144_)
  );
  sg13g2_nand2_1 _453_ (
    .A(boot_we),
    .B(boot_wdata[6]),
    .Y(_145_)
  );
  sg13g2_o21ai_1 _454_ (
    .A1(_144_),
    .A2(_142_),
    .B1(_145_),
    .Y(\sram_din[6] )
  );
  sg13g2_inv_1 _455_ (
    .A(\wdata_q[7] ),
    .Y(_146_)
  );
  sg13g2_nand2_1 _456_ (
    .A(boot_we),
    .B(boot_wdata[7]),
    .Y(_147_)
  );
  sg13g2_o21ai_1 _457_ (
    .A1(_146_),
    .A2(_142_),
    .B1(_147_),
    .Y(\sram_din[7] )
  );
  sg13g2_inv_1 _458_ (
    .A(\wdata_q[8] ),
    .Y(_148_)
  );
  sg13g2_nand2_1 _459_ (
    .A(boot_we),
    .B(boot_wdata[8]),
    .Y(_149_)
  );
  sg13g2_o21ai_1 _460_ (
    .A1(_148_),
    .A2(_142_),
    .B1(_149_),
    .Y(\sram_din[8] )
  );
  sg13g2_inv_1 _461_ (
    .A(\wdata_q[9] ),
    .Y(_150_)
  );
  sg13g2_nand2_1 _462_ (
    .A(boot_we),
    .B(boot_wdata[9]),
    .Y(_151_)
  );
  sg13g2_o21ai_1 _463_ (
    .A1(_150_),
    .A2(_142_),
    .B1(_151_),
    .Y(\sram_din[9] )
  );
  sg13g2_inv_1 _464_ (
    .A(\wdata_q[10] ),
    .Y(_152_)
  );
  sg13g2_nand2_1 _465_ (
    .A(boot_we),
    .B(boot_wdata[10]),
    .Y(_153_)
  );
  sg13g2_o21ai_1 _466_ (
    .A1(_152_),
    .A2(_142_),
    .B1(_153_),
    .Y(\sram_din[10] )
  );
  sg13g2_inv_1 _467_ (
    .A(\wdata_q[11] ),
    .Y(_154_)
  );
  sg13g2_nand2_1 _468_ (
    .A(boot_we),
    .B(boot_wdata[11]),
    .Y(_155_)
  );
  sg13g2_o21ai_1 _469_ (
    .A1(_154_),
    .A2(_142_),
    .B1(_155_),
    .Y(\sram_din[11] )
  );
  sg13g2_inv_1 _470_ (
    .A(\wdata_q[12] ),
    .Y(_156_)
  );
  sg13g2_nand2_1 _471_ (
    .A(boot_we),
    .B(boot_wdata[12]),
    .Y(_157_)
  );
  sg13g2_o21ai_1 _472_ (
    .A1(_156_),
    .A2(_142_),
    .B1(_157_),
    .Y(\sram_din[12] )
  );
  sg13g2_inv_1 _473_ (
    .A(\wdata_q[13] ),
    .Y(_158_)
  );
  sg13g2_nand2_1 _474_ (
    .A(boot_we),
    .B(boot_wdata[13]),
    .Y(_159_)
  );
  sg13g2_o21ai_1 _475_ (
    .A1(_158_),
    .A2(_142_),
    .B1(_159_),
    .Y(\sram_din[13] )
  );
  sg13g2_inv_1 _476_ (
    .A(\wdata_q[14] ),
    .Y(_160_)
  );
  sg13g2_nand2_1 _477_ (
    .A(boot_we),
    .B(boot_wdata[14]),
    .Y(_161_)
  );
  sg13g2_o21ai_1 _478_ (
    .A1(_160_),
    .A2(_142_),
    .B1(_161_),
    .Y(\sram_din[14] )
  );
  sg13g2_inv_1 _479_ (
    .A(\wdata_q[15] ),
    .Y(_162_)
  );
  sg13g2_nand2_1 _480_ (
    .A(boot_we),
    .B(boot_wdata[15]),
    .Y(_163_)
  );
  sg13g2_o21ai_1 _481_ (
    .A1(_162_),
    .A2(_142_),
    .B1(_163_),
    .Y(\sram_din[15] )
  );
  sg13g2_inv_1 _482_ (
    .A(\wdata_q[16] ),
    .Y(_164_)
  );
  sg13g2_nand2_1 _483_ (
    .A(boot_we),
    .B(boot_wdata[16]),
    .Y(_165_)
  );
  sg13g2_o21ai_1 _484_ (
    .A1(_164_),
    .A2(_142_),
    .B1(_165_),
    .Y(\sram_din[16] )
  );
  sg13g2_inv_1 _485_ (
    .A(\wdata_q[17] ),
    .Y(_166_)
  );
  sg13g2_nand2_1 _486_ (
    .A(boot_we),
    .B(boot_wdata[17]),
    .Y(_167_)
  );
  sg13g2_o21ai_1 _487_ (
    .A1(_166_),
    .A2(_142_),
    .B1(_167_),
    .Y(\sram_din[17] )
  );
  sg13g2_inv_1 _488_ (
    .A(\wdata_q[18] ),
    .Y(_168_)
  );
  sg13g2_nand2_1 _489_ (
    .A(boot_we),
    .B(boot_wdata[18]),
    .Y(_169_)
  );
  sg13g2_o21ai_1 _490_ (
    .A1(_168_),
    .A2(_142_),
    .B1(_169_),
    .Y(\sram_din[18] )
  );
  sg13g2_inv_1 _491_ (
    .A(\wdata_q[19] ),
    .Y(_170_)
  );
  sg13g2_buf_8 _492_ (
    .A(_141_),
    .X(_171_)
  );
  sg13g2_nand2_1 _493_ (
    .A(boot_we),
    .B(boot_wdata[19]),
    .Y(_172_)
  );
  sg13g2_o21ai_1 _494_ (
    .A1(_170_),
    .A2(_171_),
    .B1(_172_),
    .Y(\sram_din[19] )
  );
  sg13g2_inv_1 _495_ (
    .A(\wdata_q[20] ),
    .Y(_173_)
  );
  sg13g2_nand2_1 _496_ (
    .A(boot_we),
    .B(boot_wdata[20]),
    .Y(_174_)
  );
  sg13g2_o21ai_1 _497_ (
    .A1(_173_),
    .A2(_171_),
    .B1(_174_),
    .Y(\sram_din[20] )
  );
  sg13g2_inv_1 _498_ (
    .A(\wdata_q[21] ),
    .Y(_175_)
  );
  sg13g2_nand2_1 _499_ (
    .A(boot_we),
    .B(boot_wdata[21]),
    .Y(_176_)
  );
  sg13g2_o21ai_1 _500_ (
    .A1(_175_),
    .A2(_171_),
    .B1(_176_),
    .Y(\sram_din[21] )
  );
  sg13g2_inv_1 _501_ (
    .A(\wdata_q[22] ),
    .Y(_177_)
  );
  sg13g2_nand2_1 _502_ (
    .A(boot_we),
    .B(boot_wdata[22]),
    .Y(_178_)
  );
  sg13g2_o21ai_1 _503_ (
    .A1(_177_),
    .A2(_171_),
    .B1(_178_),
    .Y(\sram_din[22] )
  );
  sg13g2_inv_1 _504_ (
    .A(\wdata_q[23] ),
    .Y(_179_)
  );
  sg13g2_nand2_1 _505_ (
    .A(boot_we),
    .B(boot_wdata[23]),
    .Y(_180_)
  );
  sg13g2_o21ai_1 _506_ (
    .A1(_179_),
    .A2(_171_),
    .B1(_180_),
    .Y(\sram_din[23] )
  );
  sg13g2_inv_1 _507_ (
    .A(\wdata_q[24] ),
    .Y(_181_)
  );
  sg13g2_nand2_1 _508_ (
    .A(boot_we),
    .B(boot_wdata[24]),
    .Y(_182_)
  );
  sg13g2_o21ai_1 _509_ (
    .A1(_181_),
    .A2(_171_),
    .B1(_182_),
    .Y(\sram_din[24] )
  );
  sg13g2_inv_1 _510_ (
    .A(\wdata_q[25] ),
    .Y(_183_)
  );
  sg13g2_nand2_1 _511_ (
    .A(boot_we),
    .B(boot_wdata[25]),
    .Y(_184_)
  );
  sg13g2_o21ai_1 _512_ (
    .A1(_183_),
    .A2(_171_),
    .B1(_184_),
    .Y(\sram_din[25] )
  );
  sg13g2_inv_1 _513_ (
    .A(\wdata_q[26] ),
    .Y(_185_)
  );
  sg13g2_nand2_1 _514_ (
    .A(boot_we),
    .B(boot_wdata[26]),
    .Y(_186_)
  );
  sg13g2_o21ai_1 _515_ (
    .A1(_185_),
    .A2(_171_),
    .B1(_186_),
    .Y(\sram_din[26] )
  );
  sg13g2_inv_1 _516_ (
    .A(\wdata_q[27] ),
    .Y(_187_)
  );
  sg13g2_nand2_1 _517_ (
    .A(boot_we),
    .B(boot_wdata[27]),
    .Y(_188_)
  );
  sg13g2_o21ai_1 _518_ (
    .A1(_187_),
    .A2(_171_),
    .B1(_188_),
    .Y(\sram_din[27] )
  );
  sg13g2_inv_1 _519_ (
    .A(\wdata_q[28] ),
    .Y(_189_)
  );
  sg13g2_nand2_1 _520_ (
    .A(boot_we),
    .B(boot_wdata[28]),
    .Y(_190_)
  );
  sg13g2_o21ai_1 _521_ (
    .A1(_189_),
    .A2(_171_),
    .B1(_190_),
    .Y(\sram_din[28] )
  );
  sg13g2_inv_1 _522_ (
    .A(\wdata_q[29] ),
    .Y(_191_)
  );
  sg13g2_nand2_1 _523_ (
    .A(boot_we),
    .B(boot_wdata[29]),
    .Y(_192_)
  );
  sg13g2_o21ai_1 _524_ (
    .A1(_191_),
    .A2(_171_),
    .B1(_192_),
    .Y(\sram_din[29] )
  );
  sg13g2_inv_1 _525_ (
    .A(\wdata_q[30] ),
    .Y(_193_)
  );
  sg13g2_nand2_1 _526_ (
    .A(boot_we),
    .B(boot_wdata[30]),
    .Y(_194_)
  );
  sg13g2_o21ai_1 _527_ (
    .A1(_193_),
    .A2(_171_),
    .B1(_194_),
    .Y(\sram_din[30] )
  );
  sg13g2_inv_1 _528_ (
    .A(\wdata_q[31] ),
    .Y(_195_)
  );
  sg13g2_nand2_1 _529_ (
    .A(boot_we),
    .B(boot_wdata[31]),
    .Y(_196_)
  );
  sg13g2_o21ai_1 _530_ (
    .A1(_195_),
    .A2(_171_),
    .B1(_196_),
    .Y(\sram_din[31] )
  );
  sg13g2_nand4_1 _531_ (
    .A(_128_),
    .B(_129_),
    .C(_130_),
    .D(_131_),
    .Y(_197_)
  );
  sg13g2_buf_1 _532_ (
    .A(_197_),
    .X(_198_)
  );
  sg13g2_or4_1 _533_ (
    .A(_135_),
    .B(_136_),
    .C(_137_),
    .D(_138_),
    .X(_199_)
  );
  sg13g2_buf_4 _534_ (
    .A(_199_),
    .X(_200_)
  );
  sg13g2_inv_1 _535_ (
    .A(boot_we),
    .Y(_201_)
  );
  sg13g2_and3_1 _536_ (
    .A(_201_),
    .B(\read_addr_q[0] ),
    .C(\read_state_q[2] ),
    .X(_202_)
  );
  sg13g2_o21ai_1 _537_ (
    .A1(_198_),
    .A2(_200_),
    .B1(_202_),
    .Y(_203_)
  );
  sg13g2_nand4_1 _538_ (
    .A(_201_),
    .B(\awaddr_q[2] ),
    .C(_133_),
    .D(_140_),
    .Y(_204_)
  );
  sg13g2_nand2_1 _539_ (
    .A(boot_we),
    .B(boot_addr[2]),
    .Y(_205_)
  );
  sg13g2_nand3_1 _540_ (
    .A(_203_),
    .B(_204_),
    .C(_205_),
    .Y(\sram_addr[0] )
  );
  sg13g2_nor2b_1 _541_ (
    .A(boot_we),
    .B_N(\read_state_q[2] ),
    .Y(_206_)
  );
  sg13g2_buf_1 _542_ (
    .A(_206_),
    .X(_207_)
  );
  sg13g2_and2_1 _543_ (
    .A(\read_addr_q[1] ),
    .B(_207_),
    .X(_208_)
  );
  sg13g2_o21ai_1 _544_ (
    .A1(_198_),
    .A2(_200_),
    .B1(_208_),
    .Y(_209_)
  );
  sg13g2_nand4_1 _545_ (
    .A(_201_),
    .B(\awaddr_q[3] ),
    .C(_133_),
    .D(_140_),
    .Y(_210_)
  );
  sg13g2_nand2_1 _546_ (
    .A(boot_we),
    .B(boot_addr[3]),
    .Y(_211_)
  );
  sg13g2_nand3_1 _547_ (
    .A(_209_),
    .B(_210_),
    .C(_211_),
    .Y(\sram_addr[1] )
  );
  sg13g2_and2_1 _548_ (
    .A(\read_addr_q[2] ),
    .B(_207_),
    .X(_212_)
  );
  sg13g2_o21ai_1 _549_ (
    .A1(_198_),
    .A2(_200_),
    .B1(_212_),
    .Y(_213_)
  );
  sg13g2_nand4_1 _550_ (
    .A(_201_),
    .B(\awaddr_q[4] ),
    .C(_133_),
    .D(_140_),
    .Y(_214_)
  );
  sg13g2_nand2_1 _551_ (
    .A(boot_we),
    .B(boot_addr[4]),
    .Y(_215_)
  );
  sg13g2_nand3_1 _552_ (
    .A(_213_),
    .B(_214_),
    .C(_215_),
    .Y(\sram_addr[2] )
  );
  sg13g2_and2_1 _553_ (
    .A(\read_addr_q[3] ),
    .B(_207_),
    .X(_216_)
  );
  sg13g2_o21ai_1 _554_ (
    .A1(_198_),
    .A2(_200_),
    .B1(_216_),
    .Y(_217_)
  );
  sg13g2_nand4_1 _555_ (
    .A(_201_),
    .B(\awaddr_q[5] ),
    .C(_133_),
    .D(_140_),
    .Y(_218_)
  );
  sg13g2_nand2_1 _556_ (
    .A(boot_we),
    .B(boot_addr[5]),
    .Y(_219_)
  );
  sg13g2_nand3_1 _557_ (
    .A(_217_),
    .B(_218_),
    .C(_219_),
    .Y(\sram_addr[3] )
  );
  sg13g2_and2_1 _558_ (
    .A(\read_addr_q[4] ),
    .B(_207_),
    .X(_220_)
  );
  sg13g2_o21ai_1 _559_ (
    .A1(_198_),
    .A2(_200_),
    .B1(_220_),
    .Y(_221_)
  );
  sg13g2_nand4_1 _560_ (
    .A(_201_),
    .B(\awaddr_q[6] ),
    .C(_133_),
    .D(_140_),
    .Y(_222_)
  );
  sg13g2_nand2_1 _561_ (
    .A(boot_we),
    .B(boot_addr[6]),
    .Y(_223_)
  );
  sg13g2_nand3_1 _562_ (
    .A(_221_),
    .B(_222_),
    .C(_223_),
    .Y(\sram_addr[4] )
  );
  sg13g2_and2_1 _563_ (
    .A(\read_addr_q[5] ),
    .B(_207_),
    .X(_224_)
  );
  sg13g2_o21ai_1 _564_ (
    .A1(_198_),
    .A2(_200_),
    .B1(_224_),
    .Y(_225_)
  );
  sg13g2_nand4_1 _565_ (
    .A(_201_),
    .B(\awaddr_q[7] ),
    .C(_133_),
    .D(_140_),
    .Y(_226_)
  );
  sg13g2_nand2_1 _566_ (
    .A(boot_we),
    .B(boot_addr[7]),
    .Y(_227_)
  );
  sg13g2_nand3_1 _567_ (
    .A(_225_),
    .B(_226_),
    .C(_227_),
    .Y(\sram_addr[5] )
  );
  sg13g2_and2_1 _568_ (
    .A(\read_addr_q[6] ),
    .B(_207_),
    .X(_228_)
  );
  sg13g2_o21ai_1 _569_ (
    .A1(_198_),
    .A2(_200_),
    .B1(_228_),
    .Y(_229_)
  );
  sg13g2_nand4_1 _570_ (
    .A(_201_),
    .B(\awaddr_q[8] ),
    .C(_133_),
    .D(_140_),
    .Y(_230_)
  );
  sg13g2_nand2_1 _571_ (
    .A(boot_we),
    .B(boot_addr[8]),
    .Y(_231_)
  );
  sg13g2_nand3_1 _572_ (
    .A(_229_),
    .B(_230_),
    .C(_231_),
    .Y(\sram_addr[6] )
  );
  sg13g2_and2_1 _573_ (
    .A(\read_addr_q[7] ),
    .B(_207_),
    .X(_232_)
  );
  sg13g2_o21ai_1 _574_ (
    .A1(_198_),
    .A2(_200_),
    .B1(_232_),
    .Y(_233_)
  );
  sg13g2_nand4_1 _575_ (
    .A(_201_),
    .B(\awaddr_q[9] ),
    .C(_133_),
    .D(_140_),
    .Y(_234_)
  );
  sg13g2_nand2_1 _576_ (
    .A(boot_we),
    .B(boot_addr[9]),
    .Y(_235_)
  );
  sg13g2_nand3_1 _577_ (
    .A(_233_),
    .B(_234_),
    .C(_235_),
    .Y(\sram_addr[7] )
  );
  sg13g2_and2_1 _578_ (
    .A(\read_addr_q[8] ),
    .B(_207_),
    .X(_236_)
  );
  sg13g2_o21ai_1 _579_ (
    .A1(_198_),
    .A2(_200_),
    .B1(_236_),
    .Y(_237_)
  );
  sg13g2_nand4_1 _580_ (
    .A(_201_),
    .B(\awaddr_q[10] ),
    .C(_133_),
    .D(_140_),
    .Y(_238_)
  );
  sg13g2_nand2_1 _581_ (
    .A(boot_we),
    .B(boot_addr[10]),
    .Y(_239_)
  );
  sg13g2_nand3_1 _582_ (
    .A(_237_),
    .B(_238_),
    .C(_239_),
    .Y(\sram_addr[8] )
  );
  sg13g2_and2_1 _583_ (
    .A(\read_addr_q[9] ),
    .B(_207_),
    .X(_240_)
  );
  sg13g2_o21ai_1 _584_ (
    .A1(_198_),
    .A2(_200_),
    .B1(_240_),
    .Y(_241_)
  );
  sg13g2_nand4_1 _585_ (
    .A(_201_),
    .B(\awaddr_q[11] ),
    .C(_133_),
    .D(_140_),
    .Y(_242_)
  );
  sg13g2_nand2_1 _586_ (
    .A(boot_we),
    .B(boot_addr[11]),
    .Y(_243_)
  );
  sg13g2_nand3_1 _587_ (
    .A(_241_),
    .B(_242_),
    .C(_243_),
    .Y(\sram_addr[9] )
  );
  sg13g2_inv_1 _588_ (
    .A(\read_state_q[2] ),
    .Y(_244_)
  );
  sg13g2_nor2_2 _589_ (
    .A(_198_),
    .B(_200_),
    .Y(_245_)
  );
  sg13g2_nor3_1 _590_ (
    .A(boot_we),
    .B(_244_),
    .C(_245_),
    .Y(sram_ren)
  );
  sg13g2_inv_4 _591_ (
    .A(_126_),
    .Y(_000_)
  );
  sg13g2_nand2_1 _592_ (
    .A(_201_),
    .B(_142_),
    .Y(sram_wen)
  );
  sg13g2_nand3_1 _593_ (
    .A(_201_),
    .B(_244_),
    .C(_142_),
    .Y(sram_men)
  );
  sg13g2_or4_1 _594_ (
    .A(boot_we),
    .B(s_axil_bvalid),
    .C(s_axil_rvalid),
    .D(_017_),
    .X(_246_)
  );
  sg13g2_nor2_1 _595_ (
    .A(w_pending_q),
    .B(_246_),
    .Y(s_axil_wready)
  );
  sg13g2_nor2_1 _596_ (
    .A(aw_pending_q),
    .B(_246_),
    .Y(s_axil_awready)
  );
  sg13g2_nor3_1 _597_ (
    .A(aw_pending_q),
    .B(w_pending_q),
    .C(_246_),
    .Y(s_axil_arready)
  );
  sg13g2_a21o_1 _598_ (
    .A1(\wstrb_q[0] ),
    .A2(_245_),
    .B1(boot_we),
    .X(\sram_bm[0] )
  );
  sg13g2_a21o_1 _599_ (
    .A1(\wstrb_q[1] ),
    .A2(_245_),
    .B1(boot_we),
    .X(\sram_bm[10] )
  );
  sg13g2_a21o_1 _600_ (
    .A1(\wstrb_q[2] ),
    .A2(_245_),
    .B1(boot_we),
    .X(\sram_bm[16] )
  );
  sg13g2_a21o_1 _601_ (
    .A1(\wstrb_q[3] ),
    .A2(_245_),
    .B1(boot_we),
    .X(\sram_bm[24] )
  );
  sg13g2_inv_1 _602_ (
    .A(\wdata_q[0] ),
    .Y(_247_)
  );
  sg13g2_nand2_1 _603_ (
    .A(boot_we),
    .B(boot_wdata[0]),
    .Y(_248_)
  );
  sg13g2_o21ai_1 _604_ (
    .A1(_247_),
    .A2(_171_),
    .B1(_248_),
    .Y(\sram_din[0] )
  );
  sg13g2_inv_1 _605_ (
    .A(\wdata_q[1] ),
    .Y(_249_)
  );
  sg13g2_nand2_1 _606_ (
    .A(boot_we),
    .B(boot_wdata[1]),
    .Y(_250_)
  );
  sg13g2_o21ai_1 _607_ (
    .A1(_249_),
    .A2(_171_),
    .B1(_250_),
    .Y(\sram_din[1] )
  );
  sg13g2_inv_1 _608_ (
    .A(\wdata_q[2] ),
    .Y(_251_)
  );
  sg13g2_nand2_1 _609_ (
    .A(boot_we),
    .B(boot_wdata[2]),
    .Y(_252_)
  );
  sg13g2_o21ai_1 _610_ (
    .A1(_251_),
    .A2(_171_),
    .B1(_252_),
    .Y(\sram_din[2] )
  );
  sg13g2_inv_1 _611_ (
    .A(\wdata_q[3] ),
    .Y(_253_)
  );
  sg13g2_nand2_1 _612_ (
    .A(boot_we),
    .B(boot_wdata[3]),
    .Y(_254_)
  );
  sg13g2_o21ai_1 _613_ (
    .A1(_253_),
    .A2(_141_),
    .B1(_254_),
    .Y(\sram_din[3] )
  );
  sg13g2_inv_1 _614_ (
    .A(\wdata_q[4] ),
    .Y(_255_)
  );
  sg13g2_nand2_1 _615_ (
    .A(boot_we),
    .B(boot_wdata[4]),
    .Y(_256_)
  );
  sg13g2_o21ai_1 _616_ (
    .A1(_255_),
    .A2(_141_),
    .B1(_256_),
    .Y(\sram_din[4] )
  );
  sg13g2_nor2_1 _617_ (
    .A(_135_),
    .B(_136_),
    .Y(_257_)
  );
  sg13g2_nor2_1 _618_ (
    .A(s_axil_bresp[1]),
    .B(_257_),
    .Y(_258_)
  );
  sg13g2_nor2_1 _619_ (
    .A(_245_),
    .B(_258_),
    .Y(_019_)
  );
  sg13g2_nand2b_1 _620_ (
    .A_N(s_axil_bready),
    .B(s_axil_bvalid),
    .Y(_259_)
  );
  sg13g2_o21ai_1 _621_ (
    .A1(_135_),
    .A2(_136_),
    .B1(_259_),
    .Y(_020_)
  );
  sg13g2_nand4_1 _622_ (
    .A(_122_),
    .B(_123_),
    .C(s_axil_arvalid),
    .D(_124_),
    .Y(_260_)
  );
  sg13g2_a21oi_1 _623_ (
    .A1(_116_),
    .A2(_121_),
    .B1(_260_),
    .Y(_261_)
  );
  sg13g2_buf_2 _624_ (
    .A(_261_),
    .X(_262_)
  );
  sg13g2_nand2b_1 _625_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[0]),
    .Y(_263_)
  );
  sg13g2_nand2_1 _626_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[0] ),
    .Y(_264_)
  );
  sg13g2_o21ai_1 _627_ (
    .A1(_262_),
    .A2(_263_),
    .B1(_264_),
    .Y(_021_)
  );
  sg13g2_nand2b_1 _628_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[1]),
    .Y(_265_)
  );
  sg13g2_nand2_1 _629_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[1] ),
    .Y(_266_)
  );
  sg13g2_o21ai_1 _630_ (
    .A1(_262_),
    .A2(_265_),
    .B1(_266_),
    .Y(_022_)
  );
  sg13g2_nand2b_1 _631_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[2]),
    .Y(_267_)
  );
  sg13g2_nand2_1 _632_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[2] ),
    .Y(_268_)
  );
  sg13g2_o21ai_1 _633_ (
    .A1(_262_),
    .A2(_267_),
    .B1(_268_),
    .Y(_023_)
  );
  sg13g2_nand2b_1 _634_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[3]),
    .Y(_269_)
  );
  sg13g2_nand2_1 _635_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[3] ),
    .Y(_270_)
  );
  sg13g2_o21ai_1 _636_ (
    .A1(_262_),
    .A2(_269_),
    .B1(_270_),
    .Y(_024_)
  );
  sg13g2_nand2b_1 _637_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[4]),
    .Y(_271_)
  );
  sg13g2_nand2_1 _638_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[4] ),
    .Y(_272_)
  );
  sg13g2_o21ai_1 _639_ (
    .A1(_262_),
    .A2(_271_),
    .B1(_272_),
    .Y(_025_)
  );
  sg13g2_nand2b_1 _640_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[5]),
    .Y(_273_)
  );
  sg13g2_nand2_1 _641_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[5] ),
    .Y(_274_)
  );
  sg13g2_o21ai_1 _642_ (
    .A1(_262_),
    .A2(_273_),
    .B1(_274_),
    .Y(_026_)
  );
  sg13g2_nand2b_1 _643_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[6]),
    .Y(_275_)
  );
  sg13g2_nand2_1 _644_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[6] ),
    .Y(_276_)
  );
  sg13g2_o21ai_1 _645_ (
    .A1(_262_),
    .A2(_275_),
    .B1(_276_),
    .Y(_027_)
  );
  sg13g2_nand2b_1 _646_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[7]),
    .Y(_277_)
  );
  sg13g2_nand2_1 _647_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[7] ),
    .Y(_278_)
  );
  sg13g2_o21ai_1 _648_ (
    .A1(_262_),
    .A2(_277_),
    .B1(_278_),
    .Y(_028_)
  );
  sg13g2_nand2b_1 _649_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[8]),
    .Y(_279_)
  );
  sg13g2_nand2_1 _650_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[8] ),
    .Y(_280_)
  );
  sg13g2_o21ai_1 _651_ (
    .A1(_262_),
    .A2(_279_),
    .B1(_280_),
    .Y(_029_)
  );
  sg13g2_nand2b_1 _652_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[9]),
    .Y(_281_)
  );
  sg13g2_nand2_1 _653_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[9] ),
    .Y(_282_)
  );
  sg13g2_o21ai_1 _654_ (
    .A1(_262_),
    .A2(_281_),
    .B1(_282_),
    .Y(_030_)
  );
  sg13g2_nand2b_1 _655_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[10]),
    .Y(_283_)
  );
  sg13g2_nand2_1 _656_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[10] ),
    .Y(_284_)
  );
  sg13g2_o21ai_1 _657_ (
    .A1(_262_),
    .A2(_283_),
    .B1(_284_),
    .Y(_031_)
  );
  sg13g2_nand2b_1 _658_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[11]),
    .Y(_285_)
  );
  sg13g2_nand2_1 _659_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[11] ),
    .Y(_286_)
  );
  sg13g2_o21ai_1 _660_ (
    .A1(_262_),
    .A2(_285_),
    .B1(_286_),
    .Y(_032_)
  );
  sg13g2_nand2b_1 _661_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[12]),
    .Y(_287_)
  );
  sg13g2_nand2_1 _662_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[12] ),
    .Y(_288_)
  );
  sg13g2_o21ai_1 _663_ (
    .A1(_262_),
    .A2(_287_),
    .B1(_288_),
    .Y(_033_)
  );
  sg13g2_nand2b_1 _664_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[13]),
    .Y(_289_)
  );
  sg13g2_nand2_1 _665_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[13] ),
    .Y(_290_)
  );
  sg13g2_o21ai_1 _666_ (
    .A1(_262_),
    .A2(_289_),
    .B1(_290_),
    .Y(_034_)
  );
  sg13g2_nand2b_1 _667_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[14]),
    .Y(_291_)
  );
  sg13g2_nand2_1 _668_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[14] ),
    .Y(_292_)
  );
  sg13g2_o21ai_1 _669_ (
    .A1(_262_),
    .A2(_291_),
    .B1(_292_),
    .Y(_035_)
  );
  sg13g2_nand2b_1 _670_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[15]),
    .Y(_293_)
  );
  sg13g2_nand2_1 _671_ (
    .A(\read_state_q[1] ),
    .B(\sram_dout[15] ),
    .Y(_294_)
  );
  sg13g2_o21ai_1 _672_ (
    .A1(_262_),
    .A2(_293_),
    .B1(_294_),
    .Y(_036_)
  );
  sg13g2_buf_2 _673_ (
    .A(_261_),
    .X(_295_)
  );
  sg13g2_nand2b_1 _674_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[16]),
    .Y(_296_)
  );
  sg13g2_nand2_1 _675_ (
    .A(\read_state_q[1] ),
    .B(_001_),
    .Y(_297_)
  );
  sg13g2_o21ai_1 _676_ (
    .A1(_295_),
    .A2(_296_),
    .B1(_297_),
    .Y(_037_)
  );
  sg13g2_nand2b_1 _677_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[17]),
    .Y(_298_)
  );
  sg13g2_nand2_1 _678_ (
    .A(\read_state_q[1] ),
    .B(_002_),
    .Y(_299_)
  );
  sg13g2_o21ai_1 _679_ (
    .A1(_295_),
    .A2(_298_),
    .B1(_299_),
    .Y(_038_)
  );
  sg13g2_nand2b_1 _680_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[18]),
    .Y(_300_)
  );
  sg13g2_nand2_1 _681_ (
    .A(\read_state_q[1] ),
    .B(_003_),
    .Y(_301_)
  );
  sg13g2_o21ai_1 _682_ (
    .A1(_295_),
    .A2(_300_),
    .B1(_301_),
    .Y(_039_)
  );
  sg13g2_nand2b_1 _683_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[19]),
    .Y(_302_)
  );
  sg13g2_nand2_1 _684_ (
    .A(\read_state_q[1] ),
    .B(_004_),
    .Y(_303_)
  );
  sg13g2_o21ai_1 _685_ (
    .A1(_295_),
    .A2(_302_),
    .B1(_303_),
    .Y(_040_)
  );
  sg13g2_nand2b_1 _686_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[20]),
    .Y(_304_)
  );
  sg13g2_nand2_1 _687_ (
    .A(\read_state_q[1] ),
    .B(_005_),
    .Y(_305_)
  );
  sg13g2_o21ai_1 _688_ (
    .A1(_295_),
    .A2(_304_),
    .B1(_305_),
    .Y(_041_)
  );
  sg13g2_nand2b_1 _689_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[21]),
    .Y(_306_)
  );
  sg13g2_nand2_1 _690_ (
    .A(\read_state_q[1] ),
    .B(_006_),
    .Y(_307_)
  );
  sg13g2_o21ai_1 _691_ (
    .A1(_295_),
    .A2(_306_),
    .B1(_307_),
    .Y(_042_)
  );
  sg13g2_nand2b_1 _692_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[22]),
    .Y(_308_)
  );
  sg13g2_nand2_1 _693_ (
    .A(\read_state_q[1] ),
    .B(_007_),
    .Y(_309_)
  );
  sg13g2_o21ai_1 _694_ (
    .A1(_295_),
    .A2(_308_),
    .B1(_309_),
    .Y(_043_)
  );
  sg13g2_nand2b_1 _695_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[23]),
    .Y(_310_)
  );
  sg13g2_nand2_1 _696_ (
    .A(\read_state_q[1] ),
    .B(_008_),
    .Y(_311_)
  );
  sg13g2_o21ai_1 _697_ (
    .A1(_295_),
    .A2(_310_),
    .B1(_311_),
    .Y(_044_)
  );
  sg13g2_nand2b_1 _698_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[24]),
    .Y(_312_)
  );
  sg13g2_nand2_1 _699_ (
    .A(\read_state_q[1] ),
    .B(_009_),
    .Y(_313_)
  );
  sg13g2_o21ai_1 _700_ (
    .A1(_295_),
    .A2(_312_),
    .B1(_313_),
    .Y(_045_)
  );
  sg13g2_nand2b_1 _701_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[25]),
    .Y(_314_)
  );
  sg13g2_nand2_1 _702_ (
    .A(\read_state_q[1] ),
    .B(_010_),
    .Y(_315_)
  );
  sg13g2_o21ai_1 _703_ (
    .A1(_295_),
    .A2(_314_),
    .B1(_315_),
    .Y(_046_)
  );
  sg13g2_nand2b_1 _704_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[26]),
    .Y(_316_)
  );
  sg13g2_nand2_1 _705_ (
    .A(\read_state_q[1] ),
    .B(_011_),
    .Y(_317_)
  );
  sg13g2_o21ai_1 _706_ (
    .A1(_295_),
    .A2(_316_),
    .B1(_317_),
    .Y(_047_)
  );
  sg13g2_nand2b_1 _707_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[27]),
    .Y(_318_)
  );
  sg13g2_nand2_1 _708_ (
    .A(\read_state_q[1] ),
    .B(_012_),
    .Y(_319_)
  );
  sg13g2_o21ai_1 _709_ (
    .A1(_295_),
    .A2(_318_),
    .B1(_319_),
    .Y(_048_)
  );
  sg13g2_nand2b_1 _710_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[28]),
    .Y(_320_)
  );
  sg13g2_nand2_1 _711_ (
    .A(\read_state_q[1] ),
    .B(_013_),
    .Y(_321_)
  );
  sg13g2_o21ai_1 _712_ (
    .A1(_295_),
    .A2(_320_),
    .B1(_321_),
    .Y(_049_)
  );
  sg13g2_nand2b_1 _713_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[29]),
    .Y(_322_)
  );
  sg13g2_nand2_1 _714_ (
    .A(\read_state_q[1] ),
    .B(_014_),
    .Y(_323_)
  );
  sg13g2_o21ai_1 _715_ (
    .A1(_295_),
    .A2(_322_),
    .B1(_323_),
    .Y(_050_)
  );
  sg13g2_nand2b_1 _716_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[30]),
    .Y(_324_)
  );
  sg13g2_nand2_1 _717_ (
    .A(\read_state_q[1] ),
    .B(_015_),
    .Y(_325_)
  );
  sg13g2_o21ai_1 _718_ (
    .A1(_295_),
    .A2(_324_),
    .B1(_325_),
    .Y(_051_)
  );
  sg13g2_nand2b_1 _719_ (
    .A_N(\read_state_q[1] ),
    .B(s_axil_rdata[31]),
    .Y(_326_)
  );
  sg13g2_nand2_1 _720_ (
    .A(\read_state_q[1] ),
    .B(_016_),
    .Y(_327_)
  );
  sg13g2_o21ai_1 _721_ (
    .A1(_295_),
    .A2(_326_),
    .B1(_327_),
    .Y(_052_)
  );
  sg13g2_inv_1 _722_ (
    .A(s_axil_rresp[1]),
    .Y(_328_)
  );
  sg13g2_nand2_1 _723_ (
    .A(_114_),
    .B(_115_),
    .Y(_329_)
  );
  sg13g2_nand4_1 _724_ (
    .A(_117_),
    .B(_118_),
    .C(_119_),
    .D(_120_),
    .Y(_330_)
  );
  sg13g2_o21ai_1 _725_ (
    .A1(_329_),
    .A2(_330_),
    .B1(_125_),
    .Y(_331_)
  );
  sg13g2_a21oi_1 _726_ (
    .A1(_328_),
    .A2(_331_),
    .B1(\read_state_q[1] ),
    .Y(_053_)
  );
  sg13g2_nor2_1 _727_ (
    .A(s_axil_rvalid),
    .B(\read_state_q[1] ),
    .Y(_332_)
  );
  sg13g2_a22oi_1 _728_ (
    .A1(s_axil_rvalid),
    .A2(s_axil_rready),
    .B1(_331_),
    .B2(_332_),
    .Y(_054_)
  );
  sg13g2_nand2_1 _729_ (
    .A(s_axil_awvalid),
    .B(s_axil_awready),
    .Y(_333_)
  );
  sg13g2_buf_2 _730_ (
    .A(_333_),
    .X(_334_)
  );
  sg13g2_a21oi_1 _731_ (
    .A1(_122_),
    .A2(_334_),
    .B1(_257_),
    .Y(_055_)
  );
  sg13g2_mux2_1 _732_ (
    .A0(s_axil_awaddr[2]),
    .A1(\awaddr_q[2] ),
    .S(_334_),
    .X(_056_)
  );
  sg13g2_mux2_1 _733_ (
    .A0(s_axil_awaddr[3]),
    .A1(\awaddr_q[3] ),
    .S(_334_),
    .X(_057_)
  );
  sg13g2_mux2_1 _734_ (
    .A0(s_axil_awaddr[4]),
    .A1(\awaddr_q[4] ),
    .S(_334_),
    .X(_058_)
  );
  sg13g2_mux2_1 _735_ (
    .A0(s_axil_awaddr[5]),
    .A1(\awaddr_q[5] ),
    .S(_334_),
    .X(_059_)
  );
  sg13g2_mux2_1 _736_ (
    .A0(s_axil_awaddr[6]),
    .A1(\awaddr_q[6] ),
    .S(_334_),
    .X(_060_)
  );
  sg13g2_mux2_1 _737_ (
    .A0(s_axil_awaddr[7]),
    .A1(\awaddr_q[7] ),
    .S(_334_),
    .X(_061_)
  );
  sg13g2_mux2_1 _738_ (
    .A0(s_axil_awaddr[8]),
    .A1(\awaddr_q[8] ),
    .S(_334_),
    .X(_062_)
  );
  sg13g2_mux2_1 _739_ (
    .A0(s_axil_awaddr[9]),
    .A1(\awaddr_q[9] ),
    .S(_334_),
    .X(_063_)
  );
  sg13g2_mux2_1 _740_ (
    .A0(s_axil_awaddr[10]),
    .A1(\awaddr_q[10] ),
    .S(_334_),
    .X(_064_)
  );
  sg13g2_mux2_1 _741_ (
    .A0(s_axil_awaddr[11]),
    .A1(\awaddr_q[11] ),
    .S(_334_),
    .X(_065_)
  );
  sg13g2_nand2_1 _742_ (
    .A(s_axil_wvalid),
    .B(s_axil_wready),
    .Y(_335_)
  );
  sg13g2_buf_4 _743_ (
    .A(_335_),
    .X(_336_)
  );
  sg13g2_buf_8 _744_ (
    .A(_336_),
    .X(_337_)
  );
  sg13g2_a21oi_1 _745_ (
    .A1(_123_),
    .A2(_337_),
    .B1(_257_),
    .Y(_066_)
  );
  sg13g2_mux2_1 _746_ (
    .A0(s_axil_wdata[0]),
    .A1(\wdata_q[0] ),
    .S(_337_),
    .X(_067_)
  );
  sg13g2_mux2_1 _747_ (
    .A0(s_axil_wdata[1]),
    .A1(\wdata_q[1] ),
    .S(_337_),
    .X(_068_)
  );
  sg13g2_mux2_1 _748_ (
    .A0(s_axil_wdata[2]),
    .A1(\wdata_q[2] ),
    .S(_337_),
    .X(_069_)
  );
  sg13g2_mux2_1 _749_ (
    .A0(s_axil_wdata[3]),
    .A1(\wdata_q[3] ),
    .S(_337_),
    .X(_070_)
  );
  sg13g2_mux2_1 _750_ (
    .A0(s_axil_wdata[4]),
    .A1(\wdata_q[4] ),
    .S(_337_),
    .X(_071_)
  );
  sg13g2_mux2_1 _751_ (
    .A0(s_axil_wdata[5]),
    .A1(\wdata_q[5] ),
    .S(_337_),
    .X(_072_)
  );
  sg13g2_mux2_1 _752_ (
    .A0(s_axil_wdata[6]),
    .A1(\wdata_q[6] ),
    .S(_337_),
    .X(_073_)
  );
  sg13g2_mux2_1 _753_ (
    .A0(s_axil_wdata[7]),
    .A1(\wdata_q[7] ),
    .S(_337_),
    .X(_074_)
  );
  sg13g2_mux2_1 _754_ (
    .A0(s_axil_wdata[8]),
    .A1(\wdata_q[8] ),
    .S(_337_),
    .X(_075_)
  );
  sg13g2_mux2_1 _755_ (
    .A0(s_axil_wdata[9]),
    .A1(\wdata_q[9] ),
    .S(_337_),
    .X(_076_)
  );
  sg13g2_mux2_1 _756_ (
    .A0(s_axil_wdata[10]),
    .A1(\wdata_q[10] ),
    .S(_337_),
    .X(_077_)
  );
  sg13g2_mux2_1 _757_ (
    .A0(s_axil_wdata[11]),
    .A1(\wdata_q[11] ),
    .S(_337_),
    .X(_078_)
  );
  sg13g2_mux2_1 _758_ (
    .A0(s_axil_wdata[12]),
    .A1(\wdata_q[12] ),
    .S(_337_),
    .X(_079_)
  );
  sg13g2_mux2_1 _759_ (
    .A0(s_axil_wdata[13]),
    .A1(\wdata_q[13] ),
    .S(_337_),
    .X(_080_)
  );
  sg13g2_mux2_1 _760_ (
    .A0(s_axil_wdata[14]),
    .A1(\wdata_q[14] ),
    .S(_337_),
    .X(_081_)
  );
  sg13g2_buf_8 _761_ (
    .A(_336_),
    .X(_338_)
  );
  sg13g2_mux2_1 _762_ (
    .A0(s_axil_wdata[15]),
    .A1(\wdata_q[15] ),
    .S(_338_),
    .X(_082_)
  );
  sg13g2_mux2_1 _763_ (
    .A0(s_axil_wdata[16]),
    .A1(\wdata_q[16] ),
    .S(_338_),
    .X(_083_)
  );
  sg13g2_mux2_1 _764_ (
    .A0(s_axil_wdata[17]),
    .A1(\wdata_q[17] ),
    .S(_338_),
    .X(_084_)
  );
  sg13g2_mux2_1 _765_ (
    .A0(s_axil_wdata[18]),
    .A1(\wdata_q[18] ),
    .S(_338_),
    .X(_085_)
  );
  sg13g2_mux2_1 _766_ (
    .A0(s_axil_wdata[19]),
    .A1(\wdata_q[19] ),
    .S(_338_),
    .X(_086_)
  );
  sg13g2_mux2_1 _767_ (
    .A0(s_axil_wdata[20]),
    .A1(\wdata_q[20] ),
    .S(_338_),
    .X(_087_)
  );
  sg13g2_mux2_1 _768_ (
    .A0(s_axil_wdata[21]),
    .A1(\wdata_q[21] ),
    .S(_338_),
    .X(_088_)
  );
  sg13g2_mux2_1 _769_ (
    .A0(s_axil_wdata[22]),
    .A1(\wdata_q[22] ),
    .S(_338_),
    .X(_089_)
  );
  sg13g2_mux2_1 _770_ (
    .A0(s_axil_wdata[23]),
    .A1(\wdata_q[23] ),
    .S(_338_),
    .X(_090_)
  );
  sg13g2_mux2_1 _771_ (
    .A0(s_axil_wdata[24]),
    .A1(\wdata_q[24] ),
    .S(_338_),
    .X(_091_)
  );
  sg13g2_mux2_1 _772_ (
    .A0(s_axil_wdata[25]),
    .A1(\wdata_q[25] ),
    .S(_338_),
    .X(_092_)
  );
  sg13g2_mux2_1 _773_ (
    .A0(s_axil_wdata[26]),
    .A1(\wdata_q[26] ),
    .S(_338_),
    .X(_093_)
  );
  sg13g2_mux2_1 _774_ (
    .A0(s_axil_wdata[27]),
    .A1(\wdata_q[27] ),
    .S(_338_),
    .X(_094_)
  );
  sg13g2_mux2_1 _775_ (
    .A0(s_axil_wdata[28]),
    .A1(\wdata_q[28] ),
    .S(_338_),
    .X(_095_)
  );
  sg13g2_mux2_1 _776_ (
    .A0(s_axil_wdata[29]),
    .A1(\wdata_q[29] ),
    .S(_338_),
    .X(_096_)
  );
  sg13g2_mux2_1 _777_ (
    .A0(s_axil_wdata[30]),
    .A1(\wdata_q[30] ),
    .S(_338_),
    .X(_097_)
  );
  sg13g2_mux2_1 _778_ (
    .A0(s_axil_wdata[31]),
    .A1(\wdata_q[31] ),
    .S(_336_),
    .X(_098_)
  );
  sg13g2_mux2_1 _779_ (
    .A0(s_axil_wstrb[0]),
    .A1(\wstrb_q[0] ),
    .S(_336_),
    .X(_099_)
  );
  sg13g2_mux2_1 _780_ (
    .A0(s_axil_wstrb[1]),
    .A1(\wstrb_q[1] ),
    .S(_336_),
    .X(_100_)
  );
  sg13g2_mux2_1 _781_ (
    .A0(s_axil_wstrb[2]),
    .A1(\wstrb_q[2] ),
    .S(_336_),
    .X(_101_)
  );
  sg13g2_mux2_1 _782_ (
    .A0(s_axil_wstrb[3]),
    .A1(\wstrb_q[3] ),
    .S(_336_),
    .X(_102_)
  );
  sg13g2_mux2_1 _783_ (
    .A0(\read_addr_q[0] ),
    .A1(s_axil_araddr[2]),
    .S(_000_),
    .X(_103_)
  );
  sg13g2_mux2_1 _784_ (
    .A0(\read_addr_q[1] ),
    .A1(s_axil_araddr[3]),
    .S(_000_),
    .X(_104_)
  );
  sg13g2_mux2_1 _785_ (
    .A0(\read_addr_q[2] ),
    .A1(s_axil_araddr[4]),
    .S(_000_),
    .X(_105_)
  );
  sg13g2_mux2_1 _786_ (
    .A0(\read_addr_q[3] ),
    .A1(s_axil_araddr[5]),
    .S(_000_),
    .X(_106_)
  );
  sg13g2_mux2_1 _787_ (
    .A0(\read_addr_q[4] ),
    .A1(s_axil_araddr[6]),
    .S(_000_),
    .X(_107_)
  );
  sg13g2_mux2_1 _788_ (
    .A0(\read_addr_q[5] ),
    .A1(s_axil_araddr[7]),
    .S(_000_),
    .X(_108_)
  );
  sg13g2_mux2_1 _789_ (
    .A0(\read_addr_q[6] ),
    .A1(s_axil_araddr[8]),
    .S(_000_),
    .X(_109_)
  );
  sg13g2_mux2_1 _790_ (
    .A0(\read_addr_q[7] ),
    .A1(s_axil_araddr[9]),
    .S(_000_),
    .X(_110_)
  );
  sg13g2_mux2_1 _791_ (
    .A0(\read_addr_q[8] ),
    .A1(s_axil_araddr[10]),
    .S(_000_),
    .X(_111_)
  );
  sg13g2_mux2_1 _792_ (
    .A0(\read_addr_q[9] ),
    .A1(s_axil_araddr[11]),
    .S(_000_),
    .X(_112_)
  );
  sg13g2_dfrbpq_1 _793_ (
    .CLK(clk_i),
    .D(_019_),
    .Q(s_axil_bresp[1]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _794_ (
    .CLK(clk_i),
    .D(_020_),
    .Q(s_axil_bvalid),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _795_ (
    .CLK(clk_i),
    .D(_021_),
    .Q(s_axil_rdata[0]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _796_ (
    .CLK(clk_i),
    .D(_022_),
    .Q(s_axil_rdata[1]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _797_ (
    .CLK(clk_i),
    .D(_023_),
    .Q(s_axil_rdata[2]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _798_ (
    .CLK(clk_i),
    .D(_024_),
    .Q(s_axil_rdata[3]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _799_ (
    .CLK(clk_i),
    .D(_025_),
    .Q(s_axil_rdata[4]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _800_ (
    .CLK(clk_i),
    .D(_026_),
    .Q(s_axil_rdata[5]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _801_ (
    .CLK(clk_i),
    .D(_027_),
    .Q(s_axil_rdata[6]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _802_ (
    .CLK(clk_i),
    .D(_028_),
    .Q(s_axil_rdata[7]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _803_ (
    .CLK(clk_i),
    .D(_029_),
    .Q(s_axil_rdata[8]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _804_ (
    .CLK(clk_i),
    .D(_030_),
    .Q(s_axil_rdata[9]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _805_ (
    .CLK(clk_i),
    .D(_031_),
    .Q(s_axil_rdata[10]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _806_ (
    .CLK(clk_i),
    .D(_032_),
    .Q(s_axil_rdata[11]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _807_ (
    .CLK(clk_i),
    .D(_033_),
    .Q(s_axil_rdata[12]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _808_ (
    .CLK(clk_i),
    .D(_034_),
    .Q(s_axil_rdata[13]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _809_ (
    .CLK(clk_i),
    .D(_035_),
    .Q(s_axil_rdata[14]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _810_ (
    .CLK(clk_i),
    .D(_036_),
    .Q(s_axil_rdata[15]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _811_ (
    .CLK(clk_i),
    .D(_037_),
    .Q(s_axil_rdata[16]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _812_ (
    .CLK(clk_i),
    .D(_038_),
    .Q(s_axil_rdata[17]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _813_ (
    .CLK(clk_i),
    .D(_039_),
    .Q(s_axil_rdata[18]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _814_ (
    .CLK(clk_i),
    .D(_040_),
    .Q(s_axil_rdata[19]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _815_ (
    .CLK(clk_i),
    .D(_041_),
    .Q(s_axil_rdata[20]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _816_ (
    .CLK(clk_i),
    .D(_042_),
    .Q(s_axil_rdata[21]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _817_ (
    .CLK(clk_i),
    .D(_043_),
    .Q(s_axil_rdata[22]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _818_ (
    .CLK(clk_i),
    .D(_044_),
    .Q(s_axil_rdata[23]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _819_ (
    .CLK(clk_i),
    .D(_045_),
    .Q(s_axil_rdata[24]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _820_ (
    .CLK(clk_i),
    .D(_046_),
    .Q(s_axil_rdata[25]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _821_ (
    .CLK(clk_i),
    .D(_047_),
    .Q(s_axil_rdata[26]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _822_ (
    .CLK(clk_i),
    .D(_048_),
    .Q(s_axil_rdata[27]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _823_ (
    .CLK(clk_i),
    .D(_049_),
    .Q(s_axil_rdata[28]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _824_ (
    .CLK(clk_i),
    .D(_050_),
    .Q(s_axil_rdata[29]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _825_ (
    .CLK(clk_i),
    .D(_051_),
    .Q(s_axil_rdata[30]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _826_ (
    .CLK(clk_i),
    .D(_052_),
    .Q(s_axil_rdata[31]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _827_ (
    .CLK(clk_i),
    .D(_053_),
    .Q(s_axil_rresp[1]),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _828_ (
    .CLK(clk_i),
    .D(_054_),
    .Q(s_axil_rvalid),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _829_ (
    .CLK(clk_i),
    .D(_055_),
    .Q(aw_pending_q),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _830_ (
    .CLK(clk_i),
    .D(_056_),
    .Q(\awaddr_q[2] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _831_ (
    .CLK(clk_i),
    .D(_057_),
    .Q(\awaddr_q[3] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _832_ (
    .CLK(clk_i),
    .D(_058_),
    .Q(\awaddr_q[4] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _833_ (
    .CLK(clk_i),
    .D(_059_),
    .Q(\awaddr_q[5] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _834_ (
    .CLK(clk_i),
    .D(_060_),
    .Q(\awaddr_q[6] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _835_ (
    .CLK(clk_i),
    .D(_061_),
    .Q(\awaddr_q[7] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _836_ (
    .CLK(clk_i),
    .D(_062_),
    .Q(\awaddr_q[8] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _837_ (
    .CLK(clk_i),
    .D(_063_),
    .Q(\awaddr_q[9] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _838_ (
    .CLK(clk_i),
    .D(_064_),
    .Q(\awaddr_q[10] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _839_ (
    .CLK(clk_i),
    .D(_065_),
    .Q(\awaddr_q[11] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _840_ (
    .CLK(clk_i),
    .D(_066_),
    .Q(w_pending_q),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _841_ (
    .CLK(clk_i),
    .D(_067_),
    .Q(\wdata_q[0] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _842_ (
    .CLK(clk_i),
    .D(_068_),
    .Q(\wdata_q[1] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _843_ (
    .CLK(clk_i),
    .D(_069_),
    .Q(\wdata_q[2] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _844_ (
    .CLK(clk_i),
    .D(_070_),
    .Q(\wdata_q[3] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _845_ (
    .CLK(clk_i),
    .D(_071_),
    .Q(\wdata_q[4] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _846_ (
    .CLK(clk_i),
    .D(_072_),
    .Q(\wdata_q[5] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _847_ (
    .CLK(clk_i),
    .D(_073_),
    .Q(\wdata_q[6] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _848_ (
    .CLK(clk_i),
    .D(_074_),
    .Q(\wdata_q[7] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _849_ (
    .CLK(clk_i),
    .D(_075_),
    .Q(\wdata_q[8] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _850_ (
    .CLK(clk_i),
    .D(_076_),
    .Q(\wdata_q[9] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _851_ (
    .CLK(clk_i),
    .D(_077_),
    .Q(\wdata_q[10] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _852_ (
    .CLK(clk_i),
    .D(_078_),
    .Q(\wdata_q[11] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _853_ (
    .CLK(clk_i),
    .D(_079_),
    .Q(\wdata_q[12] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _854_ (
    .CLK(clk_i),
    .D(_080_),
    .Q(\wdata_q[13] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _855_ (
    .CLK(clk_i),
    .D(_081_),
    .Q(\wdata_q[14] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _856_ (
    .CLK(clk_i),
    .D(_082_),
    .Q(\wdata_q[15] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _857_ (
    .CLK(clk_i),
    .D(_083_),
    .Q(\wdata_q[16] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _858_ (
    .CLK(clk_i),
    .D(_084_),
    .Q(\wdata_q[17] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _859_ (
    .CLK(clk_i),
    .D(_085_),
    .Q(\wdata_q[18] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _860_ (
    .CLK(clk_i),
    .D(_086_),
    .Q(\wdata_q[19] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _861_ (
    .CLK(clk_i),
    .D(_087_),
    .Q(\wdata_q[20] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _862_ (
    .CLK(clk_i),
    .D(_088_),
    .Q(\wdata_q[21] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _863_ (
    .CLK(clk_i),
    .D(_089_),
    .Q(\wdata_q[22] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _864_ (
    .CLK(clk_i),
    .D(_090_),
    .Q(\wdata_q[23] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _865_ (
    .CLK(clk_i),
    .D(_091_),
    .Q(\wdata_q[24] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _866_ (
    .CLK(clk_i),
    .D(_092_),
    .Q(\wdata_q[25] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _867_ (
    .CLK(clk_i),
    .D(_093_),
    .Q(\wdata_q[26] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _868_ (
    .CLK(clk_i),
    .D(_094_),
    .Q(\wdata_q[27] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _869_ (
    .CLK(clk_i),
    .D(_095_),
    .Q(\wdata_q[28] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _870_ (
    .CLK(clk_i),
    .D(_096_),
    .Q(\wdata_q[29] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _871_ (
    .CLK(clk_i),
    .D(_097_),
    .Q(\wdata_q[30] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _872_ (
    .CLK(clk_i),
    .D(_098_),
    .Q(\wdata_q[31] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _873_ (
    .CLK(clk_i),
    .D(_099_),
    .Q(\wstrb_q[0] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _874_ (
    .CLK(clk_i),
    .D(_100_),
    .Q(\wstrb_q[1] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _875_ (
    .CLK(clk_i),
    .D(_101_),
    .Q(\wstrb_q[2] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _876_ (
    .CLK(clk_i),
    .D(_102_),
    .Q(\wstrb_q[3] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _877_ (
    .CLK(clk_i),
    .D(_103_),
    .Q(\read_addr_q[0] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _878_ (
    .CLK(clk_i),
    .D(_104_),
    .Q(\read_addr_q[1] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _879_ (
    .CLK(clk_i),
    .D(_105_),
    .Q(\read_addr_q[2] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _880_ (
    .CLK(clk_i),
    .D(_106_),
    .Q(\read_addr_q[3] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _881_ (
    .CLK(clk_i),
    .D(_107_),
    .Q(\read_addr_q[4] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _882_ (
    .CLK(clk_i),
    .D(_108_),
    .Q(\read_addr_q[5] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _883_ (
    .CLK(clk_i),
    .D(_109_),
    .Q(\read_addr_q[6] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _884_ (
    .CLK(clk_i),
    .D(_110_),
    .Q(\read_addr_q[7] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _885_ (
    .CLK(clk_i),
    .D(_111_),
    .Q(\read_addr_q[8] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _886_ (
    .CLK(clk_i),
    .D(_112_),
    .Q(\read_addr_q[9] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _887_ (
    .CLK(clk_i),
    .D(_018_),
    .Q(_017_),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _888_ (
    .CLK(clk_i),
    .D(\read_state_q[2] ),
    .Q(\read_state_q[1] ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _889_ (
    .CLK(clk_i),
    .D(_000_),
    .Q(\read_state_q[2] ),
    .RESET_B(rst_ni)
  );
  sg13g2_tiehi _890_ (
    .L_HI(_339_)
  );
  sg13g2_tielo _891_ (
    .L_LO(_340_)
  );
  sg13g2_tielo _892_ (
    .L_LO(_341_)
  );
  sg13g2_tielo _893_ (
    .L_LO(_342_)
  );
  sg13g2_tielo _894_ (
    .L_LO(_343_)
  );
  sg13g2_tielo _895_ (
    .L_LO(_344_)
  );
  sg13g2_tielo _896_ (
    .L_LO(_345_)
  );
  sg13g2_tielo _897_ (
    .L_LO(_346_)
  );
  sg13g2_tielo _898_ (
    .L_LO(_347_)
  );
  sg13g2_tielo _899_ (
    .L_LO(_348_)
  );
  sg13g2_tielo _900_ (
    .L_LO(_349_)
  );
  sg13g2_tielo _901_ (
    .L_LO(_350_)
  );
  sg13g2_tielo _902_ (
    .L_LO(_351_)
  );
  sg13g2_tielo _903_ (
    .L_LO(_352_)
  );
  sg13g2_tielo _904_ (
    .L_LO(_353_)
  );
  sg13g2_tielo _905_ (
    .L_LO(_354_)
  );
  sg13g2_tielo _906_ (
    .L_LO(_355_)
  );
  sg13g2_tielo _907_ (
    .L_LO(_356_)
  );
  sg13g2_tielo _908_ (
    .L_LO(_357_)
  );
  sg13g2_tielo _909_ (
    .L_LO(_358_)
  );
  sg13g2_tielo _910_ (
    .L_LO(_359_)
  );
  sg13g2_tielo _911_ (
    .L_LO(_360_)
  );
  sg13g2_tielo _912_ (
    .L_LO(_361_)
  );
  sg13g2_tielo _913_ (
    .L_LO(_362_)
  );
  sg13g2_tielo _914_ (
    .L_LO(_363_)
  );
  sg13g2_tielo _915_ (
    .L_LO(_364_)
  );
  sg13g2_tielo _916_ (
    .L_LO(_365_)
  );
  sg13g2_tielo _917_ (
    .L_LO(_366_)
  );
  sg13g2_tielo _918_ (
    .L_LO(_367_)
  );
  sg13g2_tielo _919_ (
    .L_LO(_368_)
  );
  sg13g2_tielo _920_ (
    .L_LO(_369_)
  );
  sg13g2_tielo _921_ (
    .L_LO(_370_)
  );
  sg13g2_tielo _922_ (
    .L_LO(_371_)
  );
  sg13g2_tielo _923_ (
    .L_LO(_372_)
  );
  sg13g2_tielo _924_ (
    .L_LO(_373_)
  );
  sg13g2_tielo _925_ (
    .L_LO(_374_)
  );
  sg13g2_tielo _926_ (
    .L_LO(_375_)
  );
  sg13g2_tielo _927_ (
    .L_LO(_376_)
  );
  sg13g2_tielo _928_ (
    .L_LO(_377_)
  );
  sg13g2_tielo _929_ (
    .L_LO(_378_)
  );
  sg13g2_tielo _930_ (
    .L_LO(_379_)
  );
  sg13g2_tielo _931_ (
    .L_LO(_380_)
  );
  sg13g2_tielo _932_ (
    .L_LO(_381_)
  );
  sg13g2_tielo _933_ (
    .L_LO(_382_)
  );
  sg13g2_tielo _934_ (
    .L_LO(_383_)
  );
  sg13g2_tielo _935_ (
    .L_LO(_384_)
  );
  sg13g2_tielo _936_ (
    .L_LO(_385_)
  );
  sg13g2_tielo _937_ (
    .L_LO(_386_)
  );
  sg13g2_tielo _938_ (
    .L_LO(_387_)
  );
  sg13g2_tielo _939_ (
    .L_LO(_388_)
  );
  sg13g2_tielo _940_ (
    .L_LO(_389_)
  );
  sg13g2_tielo _941_ (
    .L_LO(_390_)
  );
  sg13g2_tielo _942_ (
    .L_LO(_391_)
  );
  sg13g2_tielo _943_ (
    .L_LO(_392_)
  );
  sg13g2_tielo _944_ (
    .L_LO(_393_)
  );
  sg13g2_tielo _945_ (
    .L_LO(_394_)
  );
  sg13g2_tielo _946_ (
    .L_LO(_395_)
  );
  sg13g2_tielo _947_ (
    .L_LO(_396_)
  );
  sg13g2_tielo _948_ (
    .L_LO(_397_)
  );
  sg13g2_tielo _949_ (
    .L_LO(_398_)
  );
  sg13g2_tielo _950_ (
    .L_LO(_399_)
  );
  sg13g2_tielo _951_ (
    .L_LO(_400_)
  );
  sg13g2_tielo _952_ (
    .L_LO(_401_)
  );
  sg13g2_tielo _953_ (
    .L_LO(_402_)
  );
  sg13g2_tielo _954_ (
    .L_LO(_403_)
  );
  sg13g2_tielo _955_ (
    .L_LO(_404_)
  );
  sg13g2_tielo _956_ (
    .L_LO(_405_)
  );
  sg13g2_tielo _957_ (
    .L_LO(_406_)
  );
  sg13g2_tielo _958_ (
    .L_LO(_407_)
  );
  sg13g2_tielo _959_ (
    .L_LO(_408_)
  );
  sg13g2_tielo _960_ (
    .L_LO(_409_)
  );
  sg13g2_tielo _961_ (
    .L_LO(_410_)
  );
  sg13g2_tielo _962_ (
    .L_LO(_411_)
  );
  sg13g2_tielo _963_ (
    .L_LO(_412_)
  );
  sg13g2_tielo _964_ (
    .L_LO(_413_)
  );
  sg13g2_tielo _965_ (
    .L_LO(_414_)
  );
  sg13g2_tielo _966_ (
    .L_LO(_415_)
  );
  sg13g2_tielo _967_ (
    .L_LO(_416_)
  );
  sg13g2_tielo _968_ (
    .L_LO(_417_)
  );
  sg13g2_tielo _969_ (
    .L_LO(_418_)
  );
  sg13g2_buf_1 _970_ (
    .A(s_axil_bresp[1]),
    .X(s_axil_bresp[0])
  );
  sg13g2_buf_1 _971_ (
    .A(s_axil_rresp[1]),
    .X(s_axil_rresp[0])
  );
  RM_IHPSG13_1P_1024x32_c2_bm_bist u_sram (
    .A_ADDR({ \sram_addr[9] , \sram_addr[8] , \sram_addr[7] , \sram_addr[6] , \sram_addr[5] , \sram_addr[4] , \sram_addr[3] , \sram_addr[2] , \sram_addr[1] , \sram_addr[0]  }),
    .A_BIST_ADDR({ _349_, _348_, _347_, _346_, _345_, _344_, _343_, _342_, _341_, _340_ }),
    .A_BIST_BM({ _381_, _380_, _379_, _378_, _377_, _376_, _375_, _374_, _373_, _372_, _371_, _370_, _369_, _368_, _367_, _366_, _365_, _364_, _363_, _362_, _361_, _360_, _359_, _358_, _357_, _356_, _355_, _354_, _353_, _352_, _351_, _350_ }),
    .A_BIST_CLK(_382_),
    .A_BIST_DIN({ _414_, _413_, _412_, _411_, _410_, _409_, _408_, _407_, _406_, _405_, _404_, _403_, _402_, _401_, _400_, _399_, _398_, _397_, _396_, _395_, _394_, _393_, _392_, _391_, _390_, _389_, _388_, _387_, _386_, _385_, _384_, _383_ }),
    .A_BIST_EN(_415_),
    .A_BIST_MEN(_416_),
    .A_BIST_REN(_417_),
    .A_BIST_WEN(_418_),
    .A_BM({ \sram_bm[24] , \sram_bm[24] , \sram_bm[24] , \sram_bm[24] , \sram_bm[24] , \sram_bm[24] , \sram_bm[24] , \sram_bm[24] , \sram_bm[16] , \sram_bm[16] , \sram_bm[16] , \sram_bm[16] , \sram_bm[16] , \sram_bm[16] , \sram_bm[16] , \sram_bm[16] , \sram_bm[10] , \sram_bm[10] , \sram_bm[10] , \sram_bm[10] , \sram_bm[10] , \sram_bm[10] , \sram_bm[10] , \sram_bm[10] , \sram_bm[0] , \sram_bm[0] , \sram_bm[0] , \sram_bm[0] , \sram_bm[0] , \sram_bm[0] , \sram_bm[0] , \sram_bm[0]  }),
    .A_CLK(clk_i),
    .A_DIN({ \sram_din[31] , \sram_din[30] , \sram_din[29] , \sram_din[28] , \sram_din[27] , \sram_din[26] , \sram_din[25] , \sram_din[24] , \sram_din[23] , \sram_din[22] , \sram_din[21] , \sram_din[20] , \sram_din[19] , \sram_din[18] , \sram_din[17] , \sram_din[16] , \sram_din[15] , \sram_din[14] , \sram_din[13] , \sram_din[12] , \sram_din[11] , \sram_din[10] , \sram_din[9] , \sram_din[8] , \sram_din[7] , \sram_din[6] , \sram_din[5] , \sram_din[4] , \sram_din[3] , \sram_din[2] , \sram_din[1] , \sram_din[0]  }),
    .A_DLY(_339_),
    .A_DOUT({ _016_, _015_, _014_, _013_, _012_, _011_, _010_, _009_, _008_, _007_, _006_, _005_, _004_, _003_, _002_, _001_, \sram_dout[15] , \sram_dout[14] , \sram_dout[13] , \sram_dout[12] , \sram_dout[11] , \sram_dout[10] , \sram_dout[9] , \sram_dout[8] , \sram_dout[7] , \sram_dout[6] , \sram_dout[5] , \sram_dout[4] , \sram_dout[3] , \sram_dout[2] , \sram_dout[1] , \sram_dout[0]  }),
    .A_MEN(sram_men),
    .A_REN(sram_ren),
    .A_WEN(sram_wen)
  );
endmodule
