// Auto-generated by LibreLane
module peripherals_macro(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk_i,
  input rst_ni,
  input[31:0] s_axil_awaddr,
  input s_axil_awvalid,
  output s_axil_awready,
  input[31:0] s_axil_wdata,
  input[3:0] s_axil_wstrb,
  input s_axil_wvalid,
  output s_axil_wready,
  output[1:0] s_axil_bresp,
  output s_axil_bvalid,
  input s_axil_bready,
  input[31:0] s_axil_araddr,
  input s_axil_arvalid,
  output s_axil_arready,
  output[31:0] s_axil_rdata,
  output[1:0] s_axil_rresp,
  output s_axil_rvalid,
  input s_axil_rready,
  input[31:0] gpio_in,
  output[31:0] gpio_out,
  output[31:0] gpio_dir
);
endmodule
